### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/gocrawsan#1]
* [x] crawling links
* [x] setting crawling max-depth for each url
* [x] setting useragent
* [x] coloring for printing
* [ ] test code
* [x] zsh completions
* [x] get selector
* [x] prevent duplication
* [ ] error code by mode
* [x] add timeout
